// Copyright (c) 2024. ATF project organization!

//
// Created by livefish on 2/20/24.
//

#ifndef MEGACLOCKGAMEWITHTIMETRAVELLING_GAMEDEF_H
#define MEGACLOCKGAMEWITHTIMETRAVELLING_GAMEDEF_H

#endif //MEGACLOCKGAMEWITHTIMETRAVELLING_GAMEDEF_H
