// Copyright (c) 2024. ATF project organization!

//
// Created by livefish on 5/23/24.
//

#ifndef MEGACLOCKGAMEWITHTIMETRAVELLING_CAMERACOMPONENTS_H
#define MEGACLOCKGAMEWITHTIMETRAVELLING_CAMERACOMPONENTS_H

#include "camera/CameraController.h"

#endif //MEGACLOCKGAMEWITHTIMETRAVELLING_CAMERACOMPONENTS_H
